import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GameProvider } from "./context";
import React from "react";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rock, Paper, Scissor",
  description: "Generated by create next app",
  creator: "@sametcn99",
  applicationName: "Rock, Paper, Scissor",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center`}>
        <GameProvider>
          <main className="flex min-h-screen w-[30rem] flex-col items-center gap-14 px-2 py-7 uppercase text-white">
            {children}
            <Footer />
          </main>
        </GameProvider>
      </body>
    </html>
  );
}
